### ISSUE TITLE
How to handle exceptions on NotifierManager.getPushNotifier().getToken()

### ISSUE THREAD

**Issue by blackwiz4rd** [mirzemehdi/KMPNotifier#83]
**KMPNotifier and Kotlin version:**
 kmpnotifier version: 1.1.0, kotlin version: 1.9.23

**Describe the bug**
I have a doubt regarding exception handling. I see many issue on token gathering (probably they are more on firebase side because they should not happen). However, it's a bit unclear how to handle the exceptions properly in cases similar to:
- `java.io.IOException: SERVICE_NOT_AVAILABLE`

In this case I think it might be preferred to return null instead of throwing an exception, because I'm not sure the exception would be caught from common kotlin code.
E.g.

```
    suspend fun getToken() = try {
        NotifierManager.getPushNotifier().getToken()
    } catch (e: Exception) {
        null
    }
```

So this might not catch the exception properly, right?

If we agree on this I could make a PR for the resolution on android side

**In which platform bug occurs?**
android (only tested here)

**Expected behavior**
Return `null` instead of throwing exception.

**Comment by mirzemehdi** [comment]
@blackwiz4rd thanks for reporting. This issue happens when device doesn't have an internet connection. But I agree with you that, it should either return null, or make it possible to catch exceptions. I'll look into this. 

But temporary solution is that before calling `getToken` function check if the device has an internet connection. This should prevent `java.io.IOException: SERVICE_NOT_AVAILABLE`

**Comment by mirzemehdi** [comment]
Thanks for suggestion @blackwiz4rd. Now in `1.4.0` version of library in case of exception it will just return null
