### ISSUE TITLE
Support for removeListener or removeAllListener?

### ISSUE THREAD

**Issue by yushosei** [mirzemehdi/KMPNotifier#89]
Hi! 
In my case
AddListner may have duplicate calls.
Do you have any plans to officially support the removeListener function for this?

I would like to handle it in the same way as 

// Register the listener when the composable enters the composition
// and unregister it when it leaves
DisposableEffect(Unit) {
NotifierManager.addListener(notifierListener)
       onDispose {
            }
}

**Comment by not2exe** [comment]
We are also waiting for this method

**Comment by yushosei** [comment]
@mirzemehdi 
the solution will work for me, thank you!

**Comment by mirzemehdi** [comment]
@yushosei @not2exe 

just wanted to let you know that now in `1.4.0` version you can use 
```setListener(listener: Listener?)``` method to set one listener or set it as a null which will be like removeListener

**Comment by Tommyten** [comment]
Hey @mirzemehdi , I think a `removeListener` function would still be a good idea.
My use case is the following:
I have a base Notification Listener `A` that handles notifications in a certain way.
However, when I navigate to a specific screen in my app I want notifications to only be handled by Listener `B`.
Now when I navigate back from this specific screen, I have to remember to `setListener(A)`, otherwise Listener `B` will always be stuck in memory, handling my notifications.

Furthermore, I find the naimg of the `setListener` method to be suboptimal, because it is not immediately clear, that it will remove all other Listeners. But that is just my personal opinion.

**Comment by Tommyten** [comment]
@mirzemehdi Is there any reason for not providing a `removeListener()` functionality?
I can think of multiple use cases where removing a single Listener from the list of Notification Listeners would be pretty great to have, rather than removing all Listeners.
